<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { analyzeTicket, createReplyDraft, runAgent } from '../api/ai'
import { assignTicket, getTicket, updateTicketStatus } from '../api/tickets'
import { ApiError, getErrorMessage } from '../api/http'
import { auth } from '../stores/auth'
import type { AiAgentResponse, AiAnalysisResponse, AiReplyDraftResponse, TicketResponse } from '../types/api'
import { nextStatuses, priorityLabel, priorityTagType, statusLabel, statusTagType } from '../utils/ticket'

const route = useRoute(); const router = useRouter(); const ticket = ref<TicketResponse | null>(null); const loading = ref(true); const errorMessage = ref('')
const statusLoading = ref(false); const assignmentLoading = ref(false); const assigneeUserId = ref<number | undefined>(); const assignmentNotice = ref('')
const analysis = ref<AiAnalysisResponse | null>(null); const draft = ref<AiReplyDraftResponse | null>(null); const agent = ref<AiAgentResponse | null>(null)
const analysisLoading = ref(false); const draftLoading = ref(false); const agentLoading = ref(false); const aiError = ref(''); const agentQuery = ref('请结合工单上下文给出排查建议，并引用相关知识。')
const id = computed(() => Number(route.params.id)); const role = computed(() => auth.role.value); const canManage = computed(() => role.value === 'AGENT' || role.value === 'ADMIN'); const nextStatus = computed(() => ticket.value ? nextStatuses(ticket.value.status)[0] : undefined)
async function load() { loading.value = true; errorMessage.value = ''; try { ticket.value = await getTicket(id.value) } catch (error) { errorMessage.value = getErrorMessage(error, '工单详情加载失败') } finally { loading.value = false } }
async function changeStatus() { if (!ticket.value || !nextStatus.value) return; statusLoading.value = true; try { ticket.value = await updateTicketStatus(ticket.value.id, nextStatus.value); ElMessage.success(`状态已更新为${statusLabel(nextStatus.value)}`) } catch (error) { ElMessage.error(getErrorMessage(error, '状态更新失败')) } finally { statusLoading.value = false } }
async function assign() { if (!ticket.value || !assigneeUserId.value) return; assignmentLoading.value = true; assignmentNotice.value = ''; try { const result = await assignTicket(ticket.value.id, assigneeUserId.value); assignmentNotice.value = `已指派给 ${result.assigneeDisplayName || result.assigneeUsername}（用户 ID ${result.assigneeUserId}）`; ElMessage.success('指派成功') } catch (error) { ElMessage.error(getErrorMessage(error, '指派失败')) } finally { assignmentLoading.value = false } }
async function doAnalysis() { if (!ticket.value) return; analysisLoading.value = true; aiError.value = ''; try { analysis.value = await analyzeTicket(ticket.value.id) } catch (error) { aiError.value = aiMessage(error) } finally { analysisLoading.value = false } }
async function doDraft() { if (!ticket.value) return; draftLoading.value = true; aiError.value = ''; try { draft.value = await createReplyDraft(ticket.value.id) } catch (error) { aiError.value = aiMessage(error) } finally { draftLoading.value = false } }
async function doAgent() { if (!ticket.value || !agentQuery.value.trim()) return; agentLoading.value = true; aiError.value = ''; try { agent.value = await runAgent(ticket.value.id, agentQuery.value.trim()) } catch (error) { aiError.value = aiMessage(error) } finally { agentLoading.value = false } }
function aiMessage(error: unknown): string { if (error instanceof ApiError && error.status === 503) return 'AI 服务暂时不可用，核心工单业务仍可使用'; return getErrorMessage(error, 'AI 请求失败，请稍后重试') }
async function copyDraft() { if (!draft.value) return; await navigator.clipboard.writeText(draft.value.draft); ElMessage.success('草稿已复制，可人工修改后使用') }
onMounted(() => { void load() })
</script>

<template>
  <div class="page-heading"><div><el-button text @click="router.back()">← 返回列表</el-button><h2 style="margin-top: 11px">工单详情</h2><p>业务字段来自 Java TicketResponse；未在后端响应中提供的时间与处理人字段不会由前端臆造。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div>
  <el-alert v-if="errorMessage" :title="errorMessage" type="error" show-icon :closable="false" style="margin-bottom: 20px"><template #default><el-button link type="primary" @click="load">重试</el-button></template></el-alert>
  <div v-if="loading" class="panel loading-block"><el-skeleton :rows="6" animated /></div>
  <div v-else-if="ticket" class="detail-layout">
    <section><div class="panel detail-card"><div class="detail-meta"><span style="font-size:12px;color:#8290a2">TICKET #{{ ticket.id }}</span><el-tag size="small" :type="statusTagType(ticket.status)">{{ statusLabel(ticket.status) }}</el-tag><el-tag size="small" effect="plain" :type="priorityTagType(ticket.priority)">{{ priorityLabel(ticket.priority) }}优先级</el-tag></div><h2 class="detail-title">{{ ticket.title }}</h2><div class="detail-description">{{ ticket.description }}</div><div class="detail-grid"><div class="meta-item"><label>创建人</label><span>{{ ticket.creatorName }}</span></div><div class="meta-item"><label>优先级</label><span>{{ ticket.priority }}</span></div><div class="meta-item"><label>状态</label><span>{{ ticket.status }}</span></div><div class="meta-item"><label>时间 / 处理人</label><span class="not-provided">当前响应未提供</span></div></div></div>
      <div v-if="canManage" class="panel action-card"><h3>业务处理</h3><p>状态机只展示当前状态允许的下一步，后端仍会通过条件 UPDATE 做最终校验。</p><div class="action-row"><el-button v-if="nextStatus" type="primary" :loading="statusLoading" @click="changeStatus">推进至 {{ statusLabel(nextStatus) }}</el-button><span v-else class="not-provided">当前状态没有可用的下一步</span><template v-if="role === 'ADMIN'"><el-input-number v-model="assigneeUserId" :min="1" placeholder="AGENT 用户 ID" controls-position="right" /><el-button :loading="assignmentLoading" @click="assign">指派 AGENT</el-button></template></div><div v-if="assignmentNotice" class="form-note">{{ assignmentNotice }}</div></div>
    </section>
    <aside v-if="canManage" class="ai-stack"><div class="panel ai-card"><div class="ai-card-header"><div><h3>AI 辅助分析</h3><p class="helper">返回结构化分类与优先级建议，不会自动修改工单。</p></div><span class="ai-badge">建议模式</span></div><div class="ai-disclaimer">AI 输出仅供客服参考。优先级、状态与处理人仍由人工和 Java 业务规则决定。</div><el-button type="primary" plain :loading="analysisLoading" @click="doAnalysis">AI 分析</el-button><el-alert v-if="aiError" :title="aiError" type="warning" :closable="false" show-icon style="margin-top: 14px" /><div v-if="analysis" class="analysis-grid"><div class="analysis-stat"><small>分类</small><strong>{{ analysis.category }}</strong></div><div class="analysis-stat"><small>建议优先级</small><strong>{{ priorityLabel(analysis.suggestedPriority) }}</strong></div><div class="analysis-stat"><small>置信度</small><strong>{{ Math.round(Number(analysis.confidence) * 100) }}%</strong></div><div class="analysis-stat"><small>返回方式</small><strong>Structured Output</strong></div></div><div v-if="analysis" class="ai-result">{{ analysis.reason }}</div></div>
      <div class="panel ai-card"><div class="ai-card-header"><div><h3>回复草稿</h3><p class="helper">草稿可编辑、可复制，必须人工确认后使用。</p></div><span class="ai-badge">Human-in-the-loop</span></div><el-button plain :loading="draftLoading" @click="doDraft">生成回复草稿</el-button><el-input v-if="draft" v-model="draft.draft" type="textarea" :rows="7" style="margin-top: 14px" /><div v-if="draft" class="action-row" style="margin-top: 10px"><span class="ticket-subtitle">语气：{{ draft.tone }}</span><el-button size="small" @click="copyDraft">复制草稿</el-button></div></div>
      <div class="panel ai-card"><div class="ai-card-header"><div><h3>AI 辅助排查</h3><p class="helper">受控只读 Agent，展示工具调用与知识来源。</p></div><span class="ai-badge">Read-only tools</span></div><el-input v-model="agentQuery" type="textarea" :rows="3" maxlength="1000" show-word-limit /><el-button type="primary" plain :loading="agentLoading" style="margin-top: 11px" @click="doAgent">运行辅助分析</el-button><div v-if="agent" class="ai-result">{{ agent.answer }}</div><div v-if="agent" class="ticket-subtitle" style="margin-top: 9px">工具调用次数：{{ agent.toolCalls }}</div><div v-if="agent?.sources?.length" class="source-list"><div v-for="source in agent.sources" :key="source.source + source.snippet" class="source-item"><strong>{{ source.source }}</strong>{{ source.snippet }}</div></div></div></aside>
  </div>
</template>
